name: snpcall
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - gatk4=4.1.7.0
  - bcftools=1.10.2
  - bioconductor-rtracklayer=1.46.0
  - bwa=0.7.17
  - cutadapt=2.8
  - fastqc=0.11.9
  - multiqc=1.8
  - picard=2.21.9
  - qualimap=2.2.2d
  - samtools=1.10
  - snpeff=4.3.1t
  - sra-tools=2.10.1
  - r-ggplot2=3.2.1
  - r-gplots=3.0.3
  - r-gsalib=2.1
  - tabix=0.2.6
  - trim-galore=0.6.5
  - vcftools=0.1.16
  - pysam=0.15.3
