name: snpcall
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _r-mutex=1.0.1
  - alsa-lib=1.1.5
  - binutils_impl_linux-64=2.33.1
  - binutils_linux-64=2.33.1
  - bioconductor-biobase=2.46.0
  - bioconductor-biocgenerics=0.32.0
  - bioconductor-biocparallel=1.20.0
  - bioconductor-biostrings=2.54.0
  - bioconductor-delayedarray=0.12.0
  - bioconductor-genomeinfodb=1.22.0
  - bioconductor-genomeinfodbdata=1.2.2
  - bioconductor-genomicalignments=1.22.0
  - bioconductor-genomicranges=1.38.0
  - bioconductor-iranges=2.20.0
  - bioconductor-noiseq=2.30.0
  - bioconductor-rhtslib=1.18.0
  - bioconductor-rsamtools=2.2.0
  - bioconductor-rtracklayer=1.46.0
  - bioconductor-s4vectors=0.24.0
  - bioconductor-summarizedexperiment=1.16.0
  - bioconductor-xvector=0.26.0
  - bioconductor-zlibbioc=1.32.0
  - bwa=0.7.17
  - bwidget=1.9.14
  - bzip2=1.0.8
  - ca-certificates=2019.11.28
  - cairo=1.16.0
  - certifi=2019.11.28
  - cffi=1.13.2
  - chardet=3.0.4
  - click=7.0
  - coloredlogs=14.0
  - colormath=3.0.0
  - cryptography=2.8
  - curl=7.68.0
  - cutadapt=2.8
  - cycler=0.10.0
  - decorator=4.4.1
  - dnaio=0.4.1
  - fastqc=0.11.9
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=2.001
  - font-ttf-source-code-pro=2.030
  - font-ttf-ubuntu=0.83
  - fontconfig=2.13.1
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freetype=2.10.0
  - fribidi=1.0.5
  - future=0.18.2
  - gcc_impl_linux-64=7.3.0
  - gcc_linux-64=7.3.0
  - gettext=0.19.8.1
  - gfortran_impl_linux-64=7.3.0
  - gfortran_linux-64=7.3.0
  - giflib=5.2.1
  - glib=2.58.3
  - graphite2=1.3.13
  - gsl=2.6
  - gxx_impl_linux-64=7.3.0
  - gxx_linux-64=7.3.0
  - harfbuzz=2.4.0
  - hdf5=1.10.5
  - htslib=1.10.2
  - humanfriendly=7.1.1
  - icu=64.2
  - idna=2.9
  - jinja2=2.11.1
  - jpeg=9c
  - kiwisolver=1.1.0
  - krb5=1.16.4
  - lcms2=2.9
  - ld_impl_linux-64=2.33.1
  - libblas=3.8.0
  - libcblas=3.8.0
  - libcurl=7.68.0
  - libdeflate=1.3
  - libedit=3.1.20170329
  - libffi=3.2.1
  - libgcc-ng=9.2.0
  - libgfortran-ng=7.3.0
  - libgomp=9.2.0
  - libiconv=1.15
  - liblapack=3.8.0
  - libopenblas=0.3.7
  - libpng=1.6.37
  - libssh2=1.8.2
  - libstdcxx-ng=9.2.0
  - libtiff=4.1.0
  - libuuid=2.32.1
  - libxcb=1.13
  - libxml2=2.9.10
  - lz4-c=1.8.3
  - lzstring=1.0.4
  - make=4.2.1
  - markdown=3.2.1
  - markupsafe=1.1.1
  - matplotlib-base=3.1.1
  - multiqc=1.8
  - ncbi-ngs-sdk=2.10.2
  - ncurses=6.1
  - networkx=2.2
  - numpy=1.18.1
  - openjdk=11.0.1
  - openssl=1.1.1d
  - pango=1.42.4
  - pcre=8.44
  - perl=5.26.2
  - perl-app-cpanminus=1.7044
  - perl-business-isbn=3.004
  - perl-business-isbn-data=20140910.003
  - perl-carp=1.38
  - perl-constant=1.33
  - perl-data-dumper=2.173
  - perl-encode=2.88
  - perl-exporter=5.72
  - perl-extutils-makemaker=7.36
  - perl-file-path=2.16
  - perl-file-temp=0.2304
  - perl-mime-base64=3.15
  - perl-parent=0.236
  - perl-uri=1.76
  - perl-xml-libxml=2.0132
  - perl-xml-namespacesupport=1.12
  - perl-xml-sax=1.02
  - perl-xml-sax-base=1.09
  - perl-xsloader=0.24
  - picard=2.21.9
  - pigz=2.3.4
  - pip=20.0.2
  - pixman=0.38.0
  - pthread-stubs=0.4
  - pycparser=2.19
  - pyopenssl=19.1.0
  - pyparsing=2.4.6
  - pysocks=1.7.1
  - python=3.7.6
  - python-dateutil=2.8.1
  - pyyaml=5.3
  - qualimap=2.2.2d
  - r-base=3.6.2
  - r-bh=1.72.0_3
  - r-bitops=1.0_6
  - r-formatr=1.7
  - r-futile.logger=1.4.3
  - r-futile.options=1.0.1
  - r-getopt=1.20.3
  - r-lambda.r=1.2.4
  - r-lattice=0.20_40
  - r-matrix=1.2_18
  - r-matrixstats=0.55.0
  - r-optparse=1.6.4
  - r-rcurl=1.98_1.1
  - r-snow=0.4_3
  - r-xml=3.99_0.3
  - readline=8.0
  - requests=2.23.0
  - samtools=1.10
  - sed=4.7
  - setuptools=45.2.0
  - simplejson=3.17.0
  - six=1.14.0
  - snpeff=4.3.1t
  - spectra=0.0.11
  - sqlite=3.30.1
  - sra-tools=2.10.1
  - tabix=0.2.6
  - tk=8.6.10
  - tktable=2.10
  - tornado=6.0.3
  - trim-galore=0.6.5
  - urllib3=1.25.7
  - vcftools=0.1.16
  - wheel=0.34.2
  - xopen=0.8.4
  - xorg-fixesproto=5.0
  - xorg-inputproto=2.3.2
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.6.9
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxfixes=5.0.3
  - xorg-libxi=1.7.10
  - xorg-libxrender=0.9.10
  - xorg-libxtst=1.2.3
  - xorg-recordproto=1.14.2
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.4
  - yaml=0.2.2
  - zlib=1.2.11
  - zstd=1.4.4
